"""Added idempotency_key column for paymnet table

Revision ID: 982143ed9846
Revises: 5ffc35fed92c
Create Date: 2026-08-12 12:25:56.009737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982143ed9846'
down_revision: Union[str, Sequence[str], None] = '5ffc35fed92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'payments', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'idempotency_key')
    # ### end Alembic commands ###
